-- ============================================================
-- WowKids First Steps - Supabase Database Schema
-- ============================================================
-- Instructions: Copy and paste this entire file into the
-- Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- and click "Run" to create all tables and policies.
-- ============================================================

-- 1. ENQUIRIES TABLE
-- Stores all parent enquiries from the website enquiry form.
CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_name TEXT NOT NULL,
  child_name TEXT NOT NULL,
  child_dob DATE,
  child_age TEXT,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  preferred_program TEXT,
  comments TEXT,
  status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Enrolled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. PROFILES TABLE
-- Stores admin user profiles with role and approval status.
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('super_admin', 'admin')),
  is_approved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- *** BOTH TABLES MUST EXIST BEFORE CREATING POLICIES THAT REFERENCE THEM ***
-- Enable Row Level Security on enquiries
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;

-- Enable Row Level Security on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;


-- 3. RLS POLICIES FOR ENQUIRIES

-- Policy: Anyone can insert (public enquiry form submission)
CREATE POLICY "Anyone can insert enquiries"
  ON enquiries
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Policy: Only authenticated admins can view enquiries
CREATE POLICY "Admins can view enquiries"
  ON enquiries
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_approved = true
    )
  );

-- Policy: Only authenticated admins can update enquiries
CREATE POLICY "Admins can update enquiries"
  ON enquiries
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_approved = true
    )
  );

-- Policy: Only authenticated admins can delete enquiries
CREATE POLICY "Admins can delete enquiries"
  ON enquiries
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_approved = true
    )
  );


-- 4. RLS POLICIES FOR PROFILES

-- Policy: Users can view their own profile
CREATE POLICY "Users can view own profile"
  ON profiles
  FOR SELECT
  TO authenticated
  USING (id = auth.uid());

-- Policy: Super admins can view all profiles
CREATE POLICY "Super admins can view all profiles"
  ON profiles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'super_admin'
        AND profiles.is_approved = true
    )
  );

-- Policy: Super admins can update profiles (approve/reject, change roles)
CREATE POLICY "Super admins can update profiles"
  ON profiles
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'super_admin'
        AND profiles.is_approved = true
    )
  );

-- Policy: Super admins can delete profiles
CREATE POLICY "Super admins can delete profiles"
  ON profiles
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'super_admin'
        AND profiles.is_approved = true
    )
  );

-- Policy: Allow insert during sign up (via trigger)
CREATE POLICY "System can insert profiles"
  ON profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (id = auth.uid());


-- 5. AUTO-PROFILE CREATION ON SIGNUP
-- This function runs automatically when a new user signs up via Supabase Auth.
-- It creates a corresponding entry in the profiles table.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, is_approved)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'full_name',
    'admin',
    false
  );
  RETURN NEW;
END;
$$;

-- Trigger the function every time a user is created
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- 6. HELPER FUNCTION FOR CREATING SUPER ADMINS
-- This function is called by the /api/setup endpoint to create
-- the very first super admin account. It uses SECURITY DEFINER
-- to bypass RLS during the initial setup.
CREATE OR REPLACE FUNCTION public.setup_super_admin(
  target_user_id UUID,
  target_email TEXT,
  target_name TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  -- Upsert: update if profile exists, insert if not
  INSERT INTO public.profiles (id, email, full_name, role, is_approved)
  VALUES (target_user_id, target_email, target_name, 'super_admin', true)
  ON CONFLICT (id) DO UPDATE
  SET role = 'super_admin', is_approved = true, email = target_email, full_name = target_name;
END;
$$;


-- ============================================================
-- INITIAL SETUP INSTRUCTIONS
-- ============================================================
-- After running this SQL, you need to create your first
-- Super Admin account. There are two ways:
--
-- === OPTION A: Via the Admin Setup Page (Easier) ===
-- 1. First, go to your website at /admin/setup
-- 2. Follow the on-screen instructions to create your Super Admin account
-- 3. The system will automatically set your role and approval
--
-- === OPTION B: Manual via Supabase Dashboard ===
-- 1. Go to Authentication > Users > Add User
-- 2. Enter your email and a strong password
-- 3. Turn ON "Auto Confirm User"
-- 4. Click "Create User"
-- 5. Then go to SQL Editor and run:
--
--    SELECT public.setup_super_admin(
--      (SELECT id FROM auth.users WHERE email = 'your-email@example.com' LIMIT 1),
--      'your-email@example.com',
--      'Your Name'
--    );
--
-- 6. You can now log in at /admin/login with your credentials.
--
-- === INITIAL CREDENTIALS ===
-- Email: [You choose this during setup]
-- Password: [You choose this during setup]
-- Login URL: https://[your-domain].vercel.app/admin/login
--
-- IMPORTANT: Save your login credentials somewhere safe!
-- ============================================================
