-- ============================================================
-- WowKids First Steps - Supabase Database Schema
-- ============================================================
-- Instructions: Copy and paste this entire file into the
-- Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- and click "Run" to create all tables and policies.
--
-- IMPORTANT: This SQL can be safely re-run multiple times.
-- It uses IF NOT EXISTS / DROP IF EXISTS throughout.
-- ============================================================

-- 1. ENQUIRIES TABLE
-- Stores all parent enquiries from the website enquiry form.
CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_name TEXT NOT NULL,
  child_name TEXT NOT NULL,
  child_dob DATE,
  child_age TEXT,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  preferred_program TEXT,
  comments TEXT,
  status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Enrolled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. PROFILES TABLE
-- Stores admin user profiles with role and approval status.
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('super_admin', 'admin')),
  is_approved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. ENABLE ROW LEVEL SECURITY
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;


-- 4. RLS POLICIES FOR ENQUIRIES

DROP POLICY IF EXISTS "Anyone can insert enquiries" ON enquiries;
CREATE POLICY "Anyone can insert enquiries"
  ON enquiries
  FOR INSERT
  TO anon
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can view enquiries" ON enquiries;
CREATE POLICY "Admins can view enquiries"
  ON enquiries
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_approved = true
    )
  );

DROP POLICY IF EXISTS "Admins can update enquiries" ON enquiries;
CREATE POLICY "Admins can update enquiries"
  ON enquiries
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_approved = true
    )
  );

DROP POLICY IF EXISTS "Admins can delete enquiries" ON enquiries;
CREATE POLICY "Admins can delete enquiries"
  ON enquiries
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.is_approved = true
    )
  );


-- 5. RLS POLICIES FOR PROFILES

-- Policy: Users can view their own profile
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile"
  ON profiles
  FOR SELECT
  TO authenticated
  USING (id = auth.uid());

-- Policy: Super admins can view all profiles
DROP POLICY IF EXISTS "Super admins can view all profiles" ON profiles;
CREATE POLICY "Super admins can view all profiles"
  ON profiles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles AS p
      WHERE p.id = auth.uid()
        AND p.role = 'super_admin'
        AND p.is_approved = true
    )
  );

-- Policy: Super admins can update profiles (approve/reject, change roles)
DROP POLICY IF EXISTS "Super admins can update profiles" ON profiles;
CREATE POLICY "Super admins can update profiles"
  ON profiles
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles AS p
      WHERE p.id = auth.uid()
        AND p.role = 'super_admin'
        AND p.is_approved = true
    )
  );

-- Policy: Super admins can delete profiles
DROP POLICY IF EXISTS "Super admins can delete profiles" ON profiles;
CREATE POLICY "Super admins can delete profiles"
  ON profiles
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles AS p
      WHERE p.id = auth.uid()
        AND p.role = 'super_admin'
        AND p.is_approved = true
    )
  );

-- Policy: Allow insert during sign up (via trigger)
DROP POLICY IF EXISTS "System can insert profiles" ON profiles;
CREATE POLICY "System can insert profiles"
  ON profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (id = auth.uid());


-- 6. AUTO-PROFILE CREATION ON SIGNUP
-- This function runs automatically when a new user signs up via Supabase Auth.
-- It creates a corresponding entry in the profiles table.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, is_approved)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'full_name',
    'admin',
    false
  );
  RETURN NEW;
END;
$$;

-- Trigger the function every time a user is created
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- 7. HELPER FUNCTION FOR CREATING SUPER ADMINS
-- This function is called by the /api/setup endpoint to create
-- the very first super admin account. It uses SECURITY DEFINER
-- to bypass RLS during the initial setup.
CREATE OR REPLACE FUNCTION public.setup_super_admin(
  target_user_id UUID,
  target_email TEXT,
  target_name TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  -- Upsert: update if profile exists, insert if not
  INSERT INTO public.profiles (id, email, full_name, role, is_approved)
  VALUES (target_user_id, target_email, target_name, 'super_admin', true)
  ON CONFLICT (id) DO UPDATE
  SET role = 'super_admin', is_approved = true, email = target_email, full_name = target_name;
END;
$$;


-- ============================================================
-- AFTER RUNNING THIS SQL:
-- ============================================================
-- 1. Go to your website at /admin/setup
-- 2. Follow the on-screen instructions to create your Super Admin account
-- 3. Log in at /admin/login
-- ============================================================
